.SILENT:
NAME		= 	Polymorphism

CC 			= 	c++

CFLAGS		= 	-Wall -Wextra -Werror -std=c++98 -Wshadow -g

RM 			= 	rm -f

INC_PATH	=	inc/

SRC_PATH	=	src/

SRC_		=	main.cpp UPDATEFILESONMAKEFILE.YO

SRC			=	$(addprefix $(SRC_PATH), $(SRC_))

GREEN		= 	\033[0;32m

RESET		=	\033[0m

$(NAME):		$(SRC)
				$(CC) $(CFLAGS) $(SRC) -o $(NAME) -I $(INC_PATH)
				make done

all: 			$(NAME)

fclean:
				$(RM) $(NAME)

re:				fclean	all

done:
				printf "															 	\n"
				printf "$(GREEN)	$(NAME)							 			$(RESET)\n"
				printf "$(GREEN)                             _  _             _ $(RESET)\n"
				printf "$(GREEN)                            (_)| |           | |$(RESET)\n"
				printf "$(GREEN)  ____   ___   ____   ____   _ | |  ____   _ | |$(RESET)\n"
				printf "$(GREEN) / ___) / _ \ |    \ |  _ \ | || | / _  ) / || |$(RESET)\n"
				printf "$(GREEN)( (___ | |_| || | | || | | || || |( (/ / ( (_| |$(RESET)\n"
				printf "$(GREEN) \____) \___/ |_|_|_|| ||_/ |_||_| \____) \____|$(RESET)\n"
				printf "$(GREEN)                     |_|                        $(RESET)\n"
				printf "																\n"

.PHONY: 		all fclean re